config/routes.rb
TypeRacer::Application.routes.draw do
  root to: "static_pages#home"

  post "/heats/update_board", to: "heats#update_board"
  post "/heats/add_car", to: "heats#add_car"
  post "/heats/start_game", to: "heats#start_game"

  resources :users, except: :destroy
  resource :session, only: [:create, :new, :destroy]
  resources :heats, only: [:show, :new, :index]
  resources :racer_stats, only: [:index, :create]
  resources :races, only: [:show]
end

app/views/layouts/_nav_bar.html.erb
<ul class="nav navbar-nav">
	<% if signed_in? %>
		<div id="current_user"
		     data-name="<%= current_user.username %>"
				 data-id="<%= current_user.id %>">
 		</div>
		  <li>
				<%= link_to "Log out", session_url, method: :delete %>
			</li>

	<% else %>
		<div id="current_user"
		  	 data-name="Guest"
		     data-id="<%= session[:token] ||= SecureRandom.base64 %>">
		</div>
    <li>
		  <%= link_to "Sign in", new_session_url %>
		</li>
		<li>
			<%= link_to "Sign up", new_user_url %>
		</li>
	<% end %>
	<li class ="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
			Race Now!
			<b class="caret"></b>
		</a>
		<ul class="dropdown-menu">
			<li><a href="/#heats/new_normal">Enter a Race</a></li>
			<li><a href="/#heats/new_practice">Practice</a></li>
			<li><a href="/#heats/new_friend">Play With Friends</a></li>
		</ul>
	</li>
	<li>
		<a href="/#highscores">Hall of Fame</a>
	</li>
</ul>

<ul class="nav navbar-nav navbar-right">
	<li>
		<% if signed_in? %>
			<a href="/#users/<%= current_user.id %>">
			<%= current_user.username %>
		<% else %>
			<li class ="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					Guest
					<b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li>You must be signed in to view more statistics!</li>
				</ul>
			</li>
		<% end %>
	  </a>
	</li>
	<li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
			User Stats
		  <b class="caret"></b>
	  </a>
		<ul class="dropdown-menu">
			<% if signed_in? %>
			  <li>Skill Level: <%= current_user.skill_level %></li>
				<li>Average Speed: <%= current_user.wpm_avg %></li>
				<li>Races Completed: <%= current_user.total_races %></li>
			<% else %>
				<li>Skill Level: <%= session_skill %></li>
				<li>Average Speed: <%= session_wpm %></li>
				<li>Races Completed: <%= session_races %></li>
			<% end %>
		</ul>
	</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="shortcut icon" href="https://s3-us-west-1.amazonaws.com/typedasher/sprinter.ico">
	<title>TypeDasher</title>
  <%= stylesheet_link_tag    "application", media: "all"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body role="document">
	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="container">
			<a href="/"><img class="navbar-brand" src="https://s3-us-west-1.amazonaws.com/typedasher/white_label2.png" alt="TypeDasher" /></a>
		  <%= render "layouts/nav_bar" %>
		</div>
	</div>

	<div class="container theme-showcase" role="main" id="content">
		<% if flash.now[:errors] %>
			<% flash.now[:errors].each do |error| %>
				<%= error %>
			<% end %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>